m-lab/stats-pipeline

- statistics/exports/continents.sql
- statistics/exports/regions.sql
- statistics/exports/us_counties.sql
- statistics/exports/us_tracts.sql
These are the queries I used to generate the sample JSON data on GCS last week.
- Continents
- Regions
- US counties
- US census tracts
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/stats-pipeline/11)
> Add queries to export histogram tables

- statistics/queries/continent_country_histogram.sql
- statistics/queries/continent_country_region_city_histogram.sql
- statistics/queries/continent_country_region_histogram.sql
- statistics/queries/continent_histogram.sql
- statistics/queries/us_census_tracts_histogram.sql
- statistics/queries/us_county_histogram.sql
This PR updates the region query with new bucket generating code and excludes results where Mbps=0
The new bucket generating sub-query now returns 46 buckets, the first beginning at 0.00000630957
As of today, ~13539 download tests have Mbps=0, and ~169 tests between 0 and 0.00006, so if we exclude tests = 0 and start the first bucket at 0.000006... we should be including all relevant tests in the histogram without having to manually generate the buckets.
This PR also adds the continent, country, and city queries for inclusion in the stats-pipeline.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/stats-pipeline/9)
> Update region query, add queries for other geographies

- statistics/queries/continent_country_histogram.sql
- statistics/queries/continent_country_region_city_histogram.sql
- statistics/queries/continent_country_region_histogram.sql
- statistics/queries/continent_histogram.sql
- statistics/queries/us_census_tracts_histogram.sql
- statistics/queries/us_county_histogram.sql
@robertodauria identified an issue with our queries that resulted in incorrect sample counts per bucket and overall per day. 
This PR updates all queries currently used in stats-pipeline, with:
* accurate counts of tests per bucket
* adds additional fields ( `dl_total_samples | ul_total_samples | dl_stats_samples | ul_stats_samples` ) to show how many total samples (all tests from all IPs) and the total number of samples used in the daily statistics
In summary:
* `dl_samples_bucket` = the # download tests whose Max mbps measurement was in the bucket range
* the sum of all `dl_samples_bucket` values for all buckets in a given day aggregation should equal `dl_samples_day`
* `ul_samples_bucket` = the # upload tests whose Max mbps measurement was in the bucket range
* the sum of all …
> Correct query counts

- exporter/exporter.go
- exporter/exporter_test.go
This PR adds several Prometheus metrics to the exporter package:
- `stats_pipeline_exporter_queries_total`: total number of queries to run to export the current table
- `stats_pipeline_exporter_queries_processed`: number of queries that have been run so far
- `stats_pipeline_exporter_uploads_queued`: number of query workers waiting for a free upload worker
- `stats_pipeline_exporter_uploads_inflight`: number of uploads currently in flight
A preview of how these would look like on Grafana is available at https://grafana.mlab-sandbox.measurementlab.net/d/07rwXefMz/stats-pipeline-monitoring?orgId=1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/stats-pipeline/39)
> Add Prometheus metrics to monitor the "export" phase of the pipeline

- exporter/exporter.go
- exporter/exporter_test.go
This PR replaces the gauge counting the length of the upload queue with a histogram. Observations of the queue length happen every time we read a job from the channel. This gives us a much more accurate representation of the queue's state over time, where using polling might miss a lot of shorter periods with a lot of queuing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/stats-pipeline/43)
> Replace queue size counter with a histogram.

- .gitignore
- pipeline/handlers.go
- pipeline/handlers_test.go
- pipeline/headers.go
This PR lets the caller of the `/v0/pipeline` endpoint select an individual step ("histograms" or "exports") via the `step` querystring parameter. If unspecified, the current behavior of running all of them is retained.
This is useful when testing and in case the export queries are changed, since generating the histogram tables is by far the most expensive step -- and it comes first.
Also, to make this endpoint more testable, it now returns a JSON object in the response body which contains the steps that have been run and any error that occurred.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/stats-pipeline/44)
> Add "step" parameter to the /pipeline endpoint

- config.json
- histogram/table.go
- histogram/table_test.go
This PR adds `stats_pipeline_histogram_bytes_processed` to track how many bytes are used by each histogram generation query.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/stats-pipeline/48)
> Add histogram metric to track bytes used in BQ

- exporter/exporter.go
This change makes sure the partitioning field doesn't appear in the final JSON but always including it in the fields to filter out in `removeFieldsFromRow`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/stats-pipeline/50)
> Remove partitioning field when exporting data to JSON

- statistics/queries/continent_country_region_asn_histogram.sql
- statistics/queries/continent_country_region_city_asn_histogram.sql
- statistics/queries/continent_country_region_city_histogram.sql
- statistics/queries/continent_country_region_histogram.sql
- statistics/queries/us_census_tracts_asn_histogram.sql
- statistics/queries/us_census_tracts_histogram.sql
- statistics/queries/us_county_asn_histogram.sql
- statistics/queries/us_county_histogram.sql
This PR updates all queries that have annotations in `client.Geo.Region` or `client.Geo.Subdivision1ISOCode`, depending on the annotator used. For reference, there are three time periods of interest related to different annotation services and source data, which are currently being unified:
| **Geo Annotations** | Dates in use | **TCP Statistics Source** | Dates in use |
|:-------------------:|:------------:|:-------------------------:|:------------:|
| geo1, annotation-service | 2009-01 - 2017-08 | web100 | 2009-01 - 2019-11 |   |
| geo2, annotation-service | 2017-09 - 2020-02 | tcpinfo | 2019-11 - present | 
| geo2, uuid-annotator     | 2020-03 - present |  |  |
This PR has been tested with data back to 2018-01-01, so should be suitable to use for generating statistics for 2018 to …
> Update queries using "region" fields

- statistics/queries/continent_country_region_asn_histogram.sql
- statistics/queries/continent_country_region_city_asn_histogram.sql
- statistics/queries/continent_country_region_city_histogram.sql
- statistics/queries/continent_country_region_histogram.sql
- statistics/queries/us_census_tracts_asn_histogram.sql
- statistics/queries/us_census_tracts_histogram.sql
- statistics/queries/us_county_asn_histogram.sql
- statistics/queries/us_county_histogram.sql
Updates region code logic in queries that have annotations in the fields `client.Geo.region` or `client.Geo.Subdivision1ISOCode`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/stats-pipeline/56)
> Update region logic

- k8s/data-processing/config/config.json
- statistics/exports/us_counties.sql
The counties query does not return an `asn` field.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/stats-pipeline/57)
> Remove extra "asn" field from order by

- k8s/data-processing/config/config.json
The previous changed to config.json needed to be replicated in k8s/data-processing/config/config.json for the new config to be used by the k8s deployment.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/stats-pipeline/60)
> Copy config.json over to k8s/data-processing/config/config.json.

- exporter/exporter.go
- exporter/exporter_test.go
- exporter/testdata/export_query.sql
- exporter/testdata/histogram_query.sql
This PR removes the fields filtering from the stats-pipeline JSON output so that fields that already appear in the output path are also repeated in the file's content -- e.g. "asn", "year", "GEOID", ...
The partitioning field ("shard") is still removed as it has no utility for the end user.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/stats-pipeline/62)
> Remove fields filtering from JSON output

- .travis.yml
- README.md
- histogram/table.go
- histogram/table_test.go
This change adds a basic .travis.yml config for running unit tests for the stats-pipeline and reporting coverage statistics to coveralls.io and adding standard badges to the README.md.
This change also fixes some bugs that were not discovered previously because unit tests were not automatic.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/stats-pipeline/66)
> Add unit tests and coverage for stats-pipeline

- cmd/stats-pipeline/main.go
- exporter/exporter.go
- exporter/exporter_test.go
- output/writer.go
- output/writer_test.go
This change adds a new local output option in addition to GCS output.
This change adds a new `Enum` flag named `-output` with two options. The default value remains `gcs`. The new output option for `local` uses the `-bucket` flag as an output directory, and writes results to local files.
This change is to support the synthetic annotation export process.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/stats-pipeline/65)
> Add output support option for GCSWriter or LocalWriter

- config/config.go
- histogram/table.go
- histogram/table_test.go
- k8s/data-processing/config/config.json
- pipeline/handlers.go
- pipeline/handlers_test.go
This PR adds three new configuration options to the "histogram" phase (which I'm considering to rename to "query execution" or some other more generic name):
- partitioningField: the field to use to partition the output table (can be blank)
- partitioningType: the type of partitioning to use ("time" / "range" - e.g. the canary query would use `time` here, while all the existing queries would use `range` over the `shard` field)
- dateField: the DATE field to use to remove the existing rows when updating a time range. It will be different from `partitioningField` when`partitioningType` is `range`, and it's mandatory
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/stats-pipeline/68)
> Make partitioning configurable during the query phase

- statistics/queries/us_state_territories_asn_histogram.sql
- statistics/queries/us_state_territories_histogram.sql
Updates two sub-queries that referred to the wrong table. Once reviewed and merged, the two currently available years (2020, 2021) of stats for these two queries will need to be re-run.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/stats-pipeline/70)
> update two subqueries that had the wrong table name

- ANNOTATION.md
- annotation/exports/tcpinfo_annotation_export.sql
- compose-annotation-export.yaml
- config-annotation-export.json
- formatter/annotation.go
- formatter/annotation_test.go
This change adds a reference configuration for running the stats-pipeline in annotation export mode with the pusher. Together they can enumerate and generate synthetic uuid-annotation archives from the tcpinfo tables.
This change includes ANNOTATION.md with instructions for running the reference configuration for local development.
This change includes a new configuration directory `annotation` that includes an `exports` directory, following the structure of the `statatistics` directories. However, the `annotation` configuration will only ever include `exports`.
A subsequent PR will introduce the k8s configurations to run within the data-processing cluster.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> Add annotation export config for local development

- annotation/exports/tcpinfo_annotation_export.sql
- exporter/exporter.go
- formatter/annotation.go
- formatter/annotation_test.go
- formatter/stats.go
- formatter/stats_test.go
- statistics/exports/cities.sql
- statistics/exports/cities_asn.sql
- statistics/exports/continents.sql
- statistics/exports/continents_asn.sql
- statistics/exports/countries.sql
- statistics/exports/countries_asn.sql
- statistics/exports/global_asn.sql
- statistics/exports/regions.sql
- statistics/exports/regions_asn.sql
- statistics/exports/us_counties.sql
- statistics/exports/us_counties_asn.sql
- statistics/exports/us_states.sql
- statistics/exports/us_states_asn.sql
- statistics/exports/us_tracts.sql
- statistics/exports/us_tracts_asn.sql
This PR changes the Formatter interface by replacing `Where` (which returned a complete SQL WHERE clause) with `Partition` (which now returns only a partition identifier, that the SQL template can use as needed).
This change is in service of optimizing the query in `annotation/exports/tcpinfo_annotation_export.sql` to date-limit ranges in both the annotation and tcpinfo tables. With this change, typical dates only need to scan ~30-40GB (vs 400GB without date filters).
The consequence of this change is that the partition id (e.g. "shard" for statistics exports, and "date" for annotation exports) is a single parameter to the export query template. Before the `Where` method was returning an SQL clause, which makes reasoning about and optimizing the SQL export query more difficult or …
> Change Formatter.Where to .Partition w/ exporter query updates

- cloudbuild.yaml
- k8s/data-processing/deployments/annotation-export-template.yaml
- k8s/data-processing/services/annotation-export.yaml
This change adds the Kubernetes configuration for deploying the annotation-export to sandbox, staging, and production environments. The annotation-export configuration includes three containers: stats-pipeline (to produce annotation files), pusher (to archive and upload individual files), node-exporter (to monitor local disk utilization during export). This configuration uses an `emptyDir` mounted on tmpfs in RAM for faster performance. Because the stats-pipeline nodepool supports autoscaling, a new node will be created for this configuration.
A companion dashboard (not yet in version control) https://grafana.mlab-sandbox.measurementlab.net/d/XokjBPKnk/annotation-export-monitoring?orgId=1&from=now-12h&to=now allows tracking the progress of the annotation-export. The dashboard will be …
> Add k8s configuration for annotation-export

- statistics/queries/canary.sql
This greatly simplifies the client/test filter.  It uses a similar strategy to the one that we are moving toward for general debiasing and client clustering, which will eventually be implemented in public views in measurement-lab and in mlab-collaboration projects.
There are fairly good comments in the SQL to explain most of what is going on.
We expect that in a month or so, the general purpose view will be made public, at which time this query can be modified to use that view, instead of duplicating a lot of the SQL code.
The code has been tested by running a bq query manually to generate gfr_stats_z and gfr_stats_tmp tables.  These in turn can be used in the prototype canary dashboards.
https://grafana.mlab-sandbox.measurementlab.net/d/h6850_v7z/gfr-canary-vs-prod-support-both-canary-con …
> Change canary query to use simpler client filter

- exporter/exporter.go
- exporter/exporter_test.go
This fixes two race conditions detected by go test -race.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/stats-pipeline/88)
> Fix races in export_test.go

- k8s/data-processing/deployments/hopannotation1-export-template.yaml
4 workers was causing the number of INODES to drop to zero.
With 3 workers, it doesn't drop below 3mil.
Before:
https://grafana.mlab-sandbox.measurementlab.net/d/XokjBPKnj/annotation-export-monitoring?orgId=1&from=1640195880000&to=1640210280000&var-datasource=Data+Processing+%28mlab-sandbox%29&viewPanel=46
After:
https://grafana.mlab-sandbox.measurementlab.net/d/XokjBPKnj/annotation-export-monitoring?orgId=1&from=1640213760000&to=now&var-datasource=Data+Processing+%28mlab-sandbox%29&viewPanel=46
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/stats-pipeline/96)
> Decrease workers for hopannotation1 export

- ANNOTATION.md
- cloudbuild.yaml
- k8s/data-processing/jobs/hopannotation1-export-cronjob.template
This PR re-purposes the annotation-export CronJob to be used for the hopannotation1-export.
The job can be monitored in sandbox with the dashboard https://grafana.mlab-sandbox.measurementlab.net/d/XokjBPKnj/annotation-export-monitoring?orgId=1&from=1640818320000&to=now&var-datasource=Data%20Processing%20(mlab-sandbox)&refresh=1m.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/stats-pipeline/93)
> Use cron job for hopannotation1 export

- k8s/data-processing/jobs/hopannotation1-export-cronjob.template
- k8s/data-processing/jobs/stats-pipeline-cronjob.yaml.template
This changes resources from the stats-pipeline using the `batch/v1beta` API to the `batch/v1` API instead.
Part of:
* https://github.com/m-lab/etl-gardener/issues/379
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/stats-pipeline/100)
> Use batch/v1 API

- k8s/data-pipeline/deployments/hopannotation1-export-template.yaml
- k8s/data-pipeline/deployments/stats-pipeline.yaml.template
All other data-pipeline workloads have simplified nodeSelectors and node labels of the form:
`<node pool name>-node="true"`
This one slipped by and this small commit resolves that.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/stats-pipeline/118)
> Updates nodeSelector for deployments
